from .auth import AuthConfig, AuthManager, TokenInfo
from .batch import (
    AdaptiveConcurrencyController,
    batch_download,
    batch_download_sync,
    BatchDownloader,
    BatchProgress,
    EnhancedBatchDownloader,
    FileScheduler,
    FileTask,
    FileTaskStatus,
    SharedConnectionBatchDownloader,
)
from .callback import (
    BaseProgressEvent,
    BatchProgressEvent,
    CallbackChain,
    ChunkProgressEvent,
    detect_callback_mode,
    EventType,
    FileCompleteEvent,
    FileProgressEvent,
    ProgressAggregator,
    ThrottledCallback,
    UnifiedCallbackAdapter,
)
from .chunk import Chunk, ChunkManager, ChunkStatus
from .config import (
    AuthType,
    DownloadConfig,
    DownloadResult,
    ProxyConfig,
    ProxyMode,
    RetryConfig,
    RetryStrategy,
    SpeedLimitConfig,
    SpeedLimitMode,
)
from .detector import ServerCapabilities, ServerDetector
from .downloader import ChunkEvent, download_file, download_file_sync, Downloader, ProgressEvent
from .exceptions import (
    CancelledError,
    ChunkDownloadError,
    ChunkError,
    ChunkResplitError,
    ConfigurationError,
    ConnectionError,
    DownloadError,
    ForbiddenError,
    HTTPError,
    NetworkError,
    RangeNotSupportedError,
    ResourceNotFoundError,
    ResumeDataCorruptedError,
    ResumeDataNotFoundError,
    ResumeError,
    SpeedLimitExceededError,
    TimeoutError,
    ValidationError,
)
from .global_pool import GlobalThreadPool, SpeedAdaptiveController
from .i18n import (
    get_available_languages,
    gettext,
    init_language,
    LANGUAGE_ENV_VAR,
    ngettext,
    pgettext,
    set_language,
)
from .limiter import AdaptiveLimiter, SpeedLimiter, TokenBucketLimiter
from .monitor import DownloadMonitor, DownloadStats
from .proxy import ProxyDetector, ProxyInfo, ProxyManager
from .reuse import FileReuseChecker, MultiSourceManager, SharedFileRegistry
from .resume import DownloadMetadata, ResumeManager
from .scheduler import AdaptiveChunkSizer, ConnectionOptimizer, FusionScheduler, SmartScheduler
from .strategy import (
    DownloadStyle,
    DynamicStyleAllocator,
    FileProfile,
    NetworkProfile,
    StrategySelector,
    StyleDecision,
)
from .utils import SpeedCalculator
from .worker import DownloadWorker, WorkerPool
from .writer import BufferedFileWriter, DirectFileWriter

__all__ = [
    "Downloader",
    "download_file",
    "download_file_sync",
    "BatchDownloader",
    "EnhancedBatchDownloader",
    "BatchProgress",
    "FileScheduler",
    "FileTask",
    "FileTaskStatus",
    "AdaptiveConcurrencyController",
    "SharedConnectionBatchDownloader",
    "batch_download",
    "batch_download_sync",
    "ProgressEvent",
    "ChunkEvent",
    "EventType",
    "BaseProgressEvent",
    "FileProgressEvent",
    "FileCompleteEvent",
    "ChunkProgressEvent",
    "BatchProgressEvent",
    "UnifiedCallbackAdapter",
    "ThrottledCallback",
    "ProgressAggregator",
    "CallbackChain",
    "detect_callback_mode",
    "DownloadConfig",
    "DownloadResult",
    "AuthConfig",
    "AuthType",
    "TokenInfo",
    "AuthManager",
    "ProxyConfig",
    "ProxyMode",
    "ProxyDetector",
    "ProxyManager",
    "ProxyInfo",
    "SpeedLimitConfig",
    "SpeedLimitMode",
    "SpeedLimiter",
    "TokenBucketLimiter",
    "AdaptiveLimiter",
    "RetryConfig",
    "RetryStrategy",
    "ServerCapabilities",
    "ServerDetector",
    "Chunk",
    "ChunkManager",
    "ChunkStatus",
    "DownloadMonitor",
    "DownloadStats",
    "DownloadMetadata",
    "ResumeManager",
    "SmartScheduler",
    "FusionScheduler",
    "AdaptiveChunkSizer",
    "ConnectionOptimizer",
    "DownloadWorker",
    "WorkerPool",
    "SpeedCalculator",
    "BufferedFileWriter",
    "DirectFileWriter",
    "DownloadStyle",
    "StrategySelector",
    "DynamicStyleAllocator",
    "FileProfile",
    "NetworkProfile",
    "StyleDecision",
    "DownloadError",
    "NetworkError",
    "ConnectionError",
    "TimeoutError",
    "HTTPError",
    "ResourceNotFoundError",
    "ForbiddenError",
    "RangeNotSupportedError",
    "ChunkError",
    "ChunkDownloadError",
    "ChunkResplitError",
    "ResumeError",
    "ResumeDataCorruptedError",
    "ResumeDataNotFoundError",
    "SpeedLimitExceededError",
    "ConfigurationError",
    "ValidationError",
    "CancelledError",
    "GlobalThreadPool",
    "SpeedAdaptiveController",
    "FileReuseChecker",
    "MultiSourceManager",
    "SharedFileRegistry",
    "gettext",
    "ngettext",
    "pgettext",
    "set_language",
    "get_available_languages",
    "init_language",
    "LANGUAGE_ENV_VAR",
]

__version__ = "0.1.0"

init_language()
